### ISSUE TITLE
tor and curl 

### ISSUE THREAD

**Issue by YellowKing5765** [gr33n37/gr33n37-ip-changer#5]
tor and curl already installed but still tool is not working

**Comment by gr33n37** [comment]
The problem might be on your end, i have retested the script and its running perfect, perhaps you tell me the distro you are using, but if its kail, it should run perfect

**Comment by YellowKing5765** [comment]
> The problem might be on your end, i have retested the script and its running perfect, perhaps you tell me the distro you are using, but if its kail, it should run perfect

I am using Kali linux and i even done it by reinstalling the script. Btw can we talk somewhere else? like on discord or telegram?
my telegram id ---> @yellowking23
